--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GamerMJay2008/MCPEToDiscord
build-by-default: true
branches:
- master
projects:
  BetterRename:
    path: ""
    icon: "icon.png"
...
