name: BetterRename
main: GamerMJay\BetterRename\Main
author: GamerMJay
api: 4.0.0
description: Easy Rename plugin
version: 1.1.0
website: https://github.com/GamerMJay/BetterRename

commands:
 rename: 
  description: "rename your item"
  permission: rename.use

permissions:
  rename.use:
    default: op
