# BetterRename V1.0.0 by GamerMJay, licensed under Apache License 2.0!


# Messages
no-permission: "§6§lBetterRename §r§8» §cyou have no permission!"
run-ingame: "§6§lBetterRename §r§8» §crun this command ingame!"
rename-usage: "§6§lBetterRename §r§8» §cUse /rename <name>"
rename-succes: "§6§lBetterRename §r§8» §aYou have renamed The item in Your hand to §b{name}"
rename.noitem: "§6§lBetterRename §r§8» §cYou have no item in your Hand!"
